### ISSUE TITLE
Debian packages fail to install

### ISSUE THREAD

**Issue by kench** [concerto/concerto-debian#50]
> sudo dpkg -i debs/concerto-lite_2-master_all.deb
> Selecting previously unselected package concerto-lite.
> (Reading database ... 558287 files and directories currently installed.)
> Unpacking concerto-lite (from .../concerto-lite_2-master_all.deb) ...
> Setting up concerto-lite (2-master) ...
> Fetching: rake-10.4.2.gem (100%)
> Successfully installed rake-10.4.2
> Fetching: bundler-1.9.2.gem (100%)
> Successfully installed bundler-1.9.2
> 2 gems installed
> cp: cannot stat `/usr/share/concerto/config/database.yml.sample': No such file or directory
> dpkg: error processing concerto-lite (--install):
>  subprocess installed post-installation script returned error exit status 1
> Processing triggers for ureadahead ...
> Errors were encountered while processing:
> concerto-lite sudo dpkg -i debs/concerto-lite_2-master_all.deb returned exit code 1

**CI Link:** https://circleci.com/gh/concerto/concerto-debian/24

Relevant build artifacts are available here:
[concerto-full_2-master_all.deb](https://circle-artifacts.com/gh/concerto/concerto-debian/24/artifacts/0/tmp/circle-artifacts.s285vQV/debs/concerto-full_2-master_all.deb)
[concerto-lite_2-master_all.deb](https://circle-artifacts.com/gh/concerto/concerto-debian/24/artifacts/0/tmp/circle-artifacts.s285vQV/debs/concerto-lite_2-master_all.deb)
[concerto-full.lintian.log](https://circle-artifacts.com/gh/concerto/concerto-debian/24/artifacts/0/tmp/circle-artifacts.s285vQV/logs/concerto-full.lintian.log)
[concerto-lite.lintian.log](https://circle-artifacts.com/gh/concerto/concerto-debian/24/artifacts/0/tmp/circle-artifacts.s285vQV/logs/concerto-lite.lintian.log)

**Comment by kench** [comment]
It appears that the DEBIAN/postinst script depends on the presence of config/database.yml.sample from the main Concerto repository, which is no longer the case.

https://github.com/concerto/concerto-debian/blob/1db3a9e8e6d4add9c831c571edf3813724347984/concerto_lite/DEBIAN/postinst

**Comment by kench** [comment]
I have a fix ready, but I need someone to help troubleshoot why dpkg -i is hanging when I attempt to install the generated packages:

https://circleci.com/gh/concerto/concerto-debian/28

I do not have ready access to a Debian system to test these packages out:

https://circle-artifacts.com/gh/concerto/concerto-debian/28/artifacts/0/tmp/circle-artifacts.5jp1Sm0/debs/concerto-full_2-master_all.deb
https://circle-artifacts.com/gh/concerto/concerto-debian/28/artifacts/0/tmp/circle-artifacts.5jp1Sm0/debs/concerto-lite_2-master_all.deb

@augustf @mfrederickson - Can either of you try to install these packages?

**Comment by kench** [comment]
This still isn't resolved.  Building the DEBs is still broken.

**Comment by emalac** [comment]
Unable to reproduce.

**Comment by kench** [comment]
Resolving in favor of tracking issue #53.
