### ISSUE TITLE
If debs directory isn't present, build fails

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-debian#57]
Without the debs directory present at build time, the build fails and aa file called debs is created and filled with rubbish binary content from the packager.

**Comment by augustf** [comment]
134f893b9285cac075af51f2d8793674c8d75b1a creates a gitkeep for the debs directory. But that's not enough to deal with the fact that the simple lack of a directory results in a failure that cannot easily be traced. The build script requires checks for this.

**Comment by mfrederickson** [comment]
It looks like kench did some circleci work that moves the debs directory https://github.com/concerto/concerto-debian/blob/master/build-scripts/circleci_move_artifacts.sh#L3 (and creates it too in another script).  Maybe this is running at some point removing that directory?  Perhaps it should copy instead of move it?  I don't know anything about circleci.

**Comment by augustf** [comment]
Yeah-I don't know anything about it either. But it would appear that that line would create this breakage. But what's odd is how the build script reacted -- by creating a file called debs with packaging binary.

**Comment by mfrederickson** [comment]
I wouldn't think that those circleci scripts would run locally though... so I wouldn't think they would impact a build (just maybe a merge check on a commit on some travis type server somewhere).  I think your idea to check for/ensure the directory exists is a good solution here https://github.com/concerto/concerto-debian/blob/master/build-scripts/debian-common.sh#L37.

**Comment by mfrederickson** [comment]
@augustf want to add a badge for circleci to the readme? https://circleci.com/docs/status-badges

**Comment by augustf** [comment]
We can do that, but I'm not entirely convinced CircleCI is doing anything remotely useful. It doesn't seem to be building the package, at least.

**Comment by mfrederickson** [comment]
It should be.  And I think we can change the mv to a cp based on this: https://circleci.com/docs/build-artifacts

**Comment by augustf** [comment]
Cool. If you have a PR that can do a successful build, throw the badge in for sure.

**Comment by mfrederickson** [comment]
Yeah, I'll have to work on that...

**Comment by kench** [comment]
As @mfrederickson said, it's supposed to successfully produce a DEB and upload it to packagecloud for continuous deployment.

**Comment by kench** [comment]
I have it running on a test/personal packagecloud for now, but when this approach matures. I would like to make a separate release branch which has a snapshot of the latest stable/tested code and automatically creates a DEB and publishes it to a repo that players can pull from.

**Comment by kench** [comment]
I looked at the most recent CircleCI failures, and it appears that there are issues with Ubuntu (the underlying distribution used in the containerized builds) and DEB package installation.  We could just remove the lines that attempt to install the package (intended to be a sanity test) and just publish them to my staging repository on packagecloud and have several test instances attempt to update from those.

**Comment by mfrederickson** [comment]
I cannot get the full package to install under circleci because it is running under ubuntu 12.04 and the libapache2-mod-passenger was requiring rubygems which uninstalls the other rubies and puts 1.8 on there.  @kench Is it possible to have the circle ci run on a Debian 8.1 jessie instance?  I think testing that the resulting packages install successfully is a good thing... however we do it.

**Comment by kench** [comment]
CircleCI doesn't provide that option unfortunately.

**Comment by augustf** [comment]
The master as it stands now is meant to be built for Debian. But going forward, might not be a bad idea to have a way of building for other distros.
