### ISSUE TITLE
Jessie repo disappeared

### ISSUE THREAD

**Issue by hrak** [concerto/concerto-debian#69]
Not sure if this is intentional or not, but the jessie dist seems to have disappeared at `http://dl.concerto-signage.org/packages/dists/jessie` since January 1st 18:00 CET.

**Comment by augustf** [comment]
We may do some redirection in the future, but the 2.3.6 package was built with Debian 9, so you’ll want to use the stretch distribution designation.

**Comment by hrak** [comment]
The documentation in several places & the install script `https://get.concerto-signage.org/add_repo.sh` also mention/use jessie at the moment, so the installation instructions & scripts will also need to be updated.

**Comment by augustf** [comment]
Right-I believe I've gotten all of them now.
