### ISSUE TITLE
libcurl3 not available on Ubuntu 22

### ISSUE THREAD

**Issue by ssmutz** [concerto/concerto-debian#77]
```
administrator@mimir:~$ sudo apt-get install concerto-full
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 passenger : Depends: libcurl3 (>= 7.16.2) but it is not installable
             Recommends: passenger-doc (= 1:6.0.14-1~stretch1) but it is not going to be installed
             Recommends: passenger-dev (= 1:6.0.14-1~stretch1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I have libcurl4, but it doesn't allow me to install libcurl3.

**Comment by ssmutz** [comment]
I got past this by updating `/etc/apt/sources.list.d/concerto.list` and replacing 
```
deb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main
```
with
```
deb https://oss-binaries.phusionpassenger.com/apt/passenger jammy main
```

I suggest updating add_repo.sh to detect the OS's codename instead of using a static one.

**Comment by zr2d2** [comment]
Hi @ssmutz, if you look at [the code](https://github.com/concerto/concerto-debian/blob/a2cdb62d506f11c0b56e8d507387e86263826797/scripts/add_repo.sh#L7), we are attempting to do that. If you have a better way, feel free to suggest it

**Comment by ssmutz** [comment]
Ah, I didn't check the code, but was using the instructions in the readme at https://github.com/concerto/concerto.
The add_repo.sh from that page (http://get.concerto-signage.org/add_repo.sh) looks like an older version.

**Comment by zr2d2** [comment]
The larger problem I see is that (dl.concerto-signage.org)[http://dl.concerto-signage.org/packages] only has pre-built packages for stretch
